---
title: "Variations in Adoption Rates of Virtual Mental Health Care Between Provinces During the COVID-19 Pandemic Indicate Differing Preferences for Delivery of Care"
author: 
  - Chloe Thierstein
thanks: "Code and data are available at: https://github.com/cthierst/shift_to_virtual_care_analysis-.git"
date: "`r Sys.time()`"
date-format: "D MMMM YYYY"
abstract: "Accessing mental health services during the COVID-19 pandemic presented a dilemma for those seeking care in Canda. This paper examines existing literature on the quality of virtual and in-person mental health services in Canada. It also analyzes data from the Canadian Institute of Health Information to draw conclusions on the rate of adoption of virtual mental health care during the pandemic. Based on this evidence, it was found that there is a large variation in the rate of adoption between provinces, suggesting that residents of each province may maintain general preferences for delivery of care."
format: pdf
toc: TRUE
number-sections: true
bibliography: references.bib
---

# Introduction

The COVID-19 pandemic introduced many measures that, while proving successful in decreasing the transmission of COVID-19, did lead to a significant and quick increase in mental health crises for Canadians. While many in-person services transitioned to being facilitated online, many were suspended [@citerichardson]. Leading to fewer services being available for a much greater demand. Calls for expanding asynchronous virtual mental health (AVMH) resources became prominent as many argue that their implementation would provide excellent support for those coping with adverse mental health issues due to the pandemic [@citerichardson]. However, research demonstrates that despite efforts to promote these services, they have yet to be accessed effectively [@citerichardson]. The data came from the Canadian Institute of Health Information (CIHI) and is used to examine the relationships between the province, age, modality, fiscal quarter and the number of services over two periods, 2019-2020 and 2020-2021 [@citecihi]. This analysis allows us to explore how provincial regulations and policy influence adoption rates of virtual mental health services.

A top insight found was that despite all provinces citing significant concerns over mental health during the pandemic, rates at which these services were accessed remained relatively low overall, with some provinces, like Alberta, maintaining higher levels of in-person services despite restrictions due to the pandemic. This finding suggests that virtual mental health care adoption varies significantly by province based on provincial regulation and policy and may be impacted by general public sentiment. Additionally, it was found that the adoption rate was inconsistent across fiscal quarters, with many provinces having extreme variations in virtual mental health care rates between quarters. 

Examining this data allows us to develop further insight into the effects of provincial regulations and policy on the implementation of evolving mental health care treatment during a unique period, such as the COVID-19 pandemic.

# Data {#sec-data}

## Data Management {#sec-first-point}

This paper utilizes the R statistical programming language [@citeR].

# Model {#sec-model}

# Results {#sec-results}

# Discussion {#sec-discussion}

\newpage

\appendix

# Appendix {#sec-appendix}

\newpage

# References 


